### ISSUE TITLE
Receive new item

### ISSUE THREAD

**Issue by ghost** [mostr/angular-ui-multi-sortable#15] opened 2015-02-13 10:04 UTC
Hello,

First of all, thank you for your wonderful directive. Just wondering any plans to make it work in conjunction with jQuery draggable? I'm speaking about situation when sortable list receives new element. http://jqueryui.com/draggable/#sortable

Thank you.

**Comment by mostr** [comment] 2015-02-13 18:25
I had no plans to work on this directive anymore as it was intended to support Angular 1.1.x versions. Do you still use 1.1? If not please take a look at https://github.com/angular-ui/ui-sortable. Folks there do pretty good job and might have what you need. If not let me know, I'll try to help you somehow.

**Comment by ghost** [comment] 2015-02-13 20:52
Thank you for your answer. I've achieved similar result by using cloning feature. http://codepen.io/thgreasi/pen/qmvhG

**Comment by mostr** [comment] 2015-02-13 21:23
Good to hear that, so I'm closing this one.

**Closed as completed by mostr** 2015-02-13 21:23 UTC
